### ISSUE TITLE
Linked containers name themselves weirdly

### ISSUE THREAD

**Issue by tcoats** [metocean/ducke#8]
@sfister experienced some weirdly named containers when using linked containers

I haven't been able to reproduce locally. The following tug file works perfectly. Perhaps it's an ordering issue?

```yml
test1:
  image: ubuntu
  command: ping google.com

test2:
  image: ubuntu
  command: ping google.com
  links:
  - "test_test1_1:first"
```
